# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install && npm test
    - name: Upload reports to Katalon TestOps
      uses: katalon-studio/report-uploader@v0.0.7.11
      env:
        PASSWORD: ${{ secrets.KATALON_API_KEY }}
        PROJECT_ID: 50236
        TYPE: junit
        REPORT_PATH: ${{ github.workspace }}/reports
